/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */

/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module 'sst' {
  export interface Resource {
    AdminSite: {
      type: 'sst.aws.StaticSite';
      url: string;
    };
    AgentEventsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AgentJobsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AlertsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    Api: {
      name: string;
      type: 'sst.aws.Function';
      url: string;
    };
    AuditsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AuthCallback: {
      name: string;
      type: 'sst.aws.Function';
      url: string;
    };
    CostsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    ProjectsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    ResourcesTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    ScheduleExecutor: {
      name: string;
      type: 'sst.aws.Function';
    };
    SchedulesTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    UsersTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
