/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */

/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module 'sst' {
  export interface Resource {
    AdminSite: {
      type: 'sst.aws.StaticSite';
      url: string;
    };
    AgentConversationsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AgentEventsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AgentFlagsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AgentJobsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AgentSessionsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AgentSpendLogTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AlertsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AnthropicApiKey: {
      type: 'sst.sst.Secret';
      value: string;
    };
    Api: {
      name: string;
      type: 'sst.aws.Function';
      url: string;
    };
    AppsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AttentionItemsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AuditsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AuthCallback: {
      name: string;
      type: 'sst.aws.Function';
      url: string;
    };
    BrownfieldGithubPat: {
      type: 'sst.sst.Secret';
      value: string;
    };
    CloudWatchAlarmsTopic: {
      arn: string;
      type: 'sst.aws.SnsTopic';
    };
    CostsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    EpicWorkflowsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    FixCyclesTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    FreeAgentConversationsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    FreeAgentSessionsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    GithubPat: {
      type: 'sst.sst.Secret';
      value: string;
    };
    PartyInlineQuestionsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    PartyProjectsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    PartySessionsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    PlansTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    ProjectRegistryTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    ProjectsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    PushSubscriptionsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    ReflectionsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    RemediationPoliciesTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    ResourcesTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    ScheduleExecutor: {
      name: string;
      type: 'sst.aws.Function';
    };
    SchedulesTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    TimingSummaryTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    UsersTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    WaveConflictsTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
