/**
 * Bootstrap Scan — Codebase Scanner for Brownfield Projects
 * Story MY-6.1
 *
 * Scans an existing project's file tree and generates wiki articles for every
 * relevant source file, enabling existing projects to be brought into the
 * knowledge graph without manual documentation.
 *
 * Usage:
 *   node bootstrap-scan.mjs --project spyhunter --dir /home/ubuntu/projects/spyhunter
 *   node bootstrap-scan.mjs --project spyhunter --dir /path --batch-size 15
 *   node bootstrap-scan.mjs --project spyhunter --dir /path --json
 *
 * Exports:
 *   bootstrapScan(projectId, workingDir, opts) — main entry point
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from 'fs';
import { join, relative, extname, dirname, basename, sep } from 'path';
import { execSync } from 'child_process';
import { createHash } from 'crypto';

// ── Configuration ──

const SUPPORTED_EXTENSIONS = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
  '.py',
  '.md',
  '.json',
  '.yaml', '.yml',
  '.sh',
  '.css', '.scss', '.html',
]);

const EXCLUDED_DIRS = new Set([
  'node_modules', '.git', 'dist', 'build', '.next', 'coverage',
  '.mycelium', 'knowledge', '__pycache__', '.cache', '.turbo',
  '.vercel', '.output', '.nuxt', '.svelte-kit', 'out',
  '.pytest_cache', '.tox', 'venv', '.venv', 'env',
]);

const DEFAULT_BATCH_SIZE = 20;

// ── Wiki directory structure ──

const WIKI_DIRS = [
  'code', 'decisions', 'requirements', 'discovery',
  'planning', 'solutioning', 'qa', 'system', 'archive',
];

// ── Helpers ──

function log(level, msg, data = {}) {
  const prefix = {
    info: '\x1b[36mINFO\x1b[0m',
    warn: '\x1b[33mWARN\x1b[0m',
    error: '\x1b[31mERROR\x1b[0m',
    debug: '\x1b[90mDEBG\x1b[0m',
  };
  const ts = new Date().toISOString();
  const extra = Object.keys(data).length ? ` ${JSON.stringify(data)}` : '';
  console.log(`[${ts}] ${prefix[level] || level} [bootstrap-scan] ${msg}${extra}`);
}

function toSlug(filePath) {
  // Convert path separators to -- for wiki slug
  return filePath.replace(/\//g, '--').replace(/\\/g, '--');
}

function toArticlePath(slug) {
  return `code/${slug}`;
}

function today() {
  return new Date().toISOString().split('T')[0];
}

// ── File Discovery ──

/**
 * Recursively discover all relevant source files, excluding generated directories.
 */
function discoverFiles(rootDir) {
  const files = [];

  function walk(dir) {
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch (err) {
      log('warn', `Cannot read directory: ${dir}`, { error: err.message });
      return;
    }

    for (const entry of entries) {
      const fullPath = join(dir, entry.name);

      if (entry.isDirectory()) {
        if (!EXCLUDED_DIRS.has(entry.name)) {
          walk(fullPath);
        }
        continue;
      }

      if (entry.isFile()) {
        const ext = extname(entry.name);
        if (SUPPORTED_EXTENSIONS.has(ext)) {
          files.push(fullPath);
        }
      }
    }
  }

  walk(rootDir);
  return files;
}

/**
 * Sort files by directory depth (shallow first) for better dependency context.
 */
function sortByDepth(files, rootDir) {
  return files.sort((a, b) => {
    const relA = relative(rootDir, a);
    const relB = relative(rootDir, b);
    const depthA = relA.split(sep).length;
    const depthB = relB.split(sep).length;
    if (depthA !== depthB) return depthA - depthB;
    return relA.localeCompare(relB);
  });
}

/**
 * Split array into batches of given size.
 */
function chunk(arr, size) {
  const batches = [];
  for (let i = 0; i < arr.length; i += size) {
    batches.push(arr.slice(i, i + size));
  }
  return batches;
}

// ── Wiki Structure Initialization ──

/**
 * Initialize the knowledge/ directory structure.
 * Equivalent to init-wiki.sh but implemented in JS for portability.
 */
function initWikiStructure(workingDir, projectId) {
  const knowledgeDir = join(workingDir, 'knowledge');
  const myceliumDir = join(workingDir, '.mycelium');

  // Create knowledge directories
  for (const subdir of WIKI_DIRS) {
    mkdirSync(join(knowledgeDir, subdir), { recursive: true });
  }

  // Create .mycelium directory
  mkdirSync(myceliumDir, { recursive: true });

  // Create index.md if it doesn't exist
  const indexPath = join(knowledgeDir, 'index.md');
  if (!existsSync(indexPath)) {
    writeFileSync(indexPath, [
      '---',
      `title: Knowledge Index — ${projectId}`,
      'type: system',
      'phase: system',
      'status: active',
      `created: ${today()}`,
      `updated: ${today()}`,
      '---',
      '',
      '# Knowledge Index',
      '',
      '_This index is auto-generated by the bootstrap pipeline._',
      '',
      '## Articles',
      '',
      '| Title | Type | Phase | Status | Path |',
      '|-------|------|-------|--------|------|',
      '',
    ].join('\n'));
  }

  // Create log.md if it doesn't exist
  const logPath = join(knowledgeDir, 'log.md');
  if (!existsSync(logPath)) {
    writeFileSync(logPath, [
      '---',
      `title: Operations Log — ${projectId}`,
      'type: system',
      'phase: system',
      'status: active',
      `created: ${today()}`,
      `updated: ${today()}`,
      '---',
      '',
      '# Operations Log',
      '',
      '_Append-only log of knowledge graph operations._',
      '',
    ].join('\n'));
  }

  log('info', `Initialized wiki structure at ${knowledgeDir}`);
  return knowledgeDir;
}

// ── Source File Analysis ──

/**
 * Analyze a source file and extract metadata for wiki article generation.
 */
function analyzeFile(filePath, rootDir) {
  let content;
  try {
    content = readFileSync(filePath, 'utf-8');
  } catch (err) {
    log('warn', `Cannot read file: ${filePath}`, { error: err.message });
    return null;
  }

  const relPath = relative(rootDir, filePath);
  const ext = extname(filePath);
  const lines = content.split('\n');

  const analysis = {
    relPath,
    slug: toSlug(relPath),
    ext,
    lineCount: lines.length,
    content,
    purpose: '',
    exports: [],
    imports: [],
    tags: [],
  };

  // Infer purpose from file location and content
  analysis.purpose = inferPurpose(relPath, content, ext);

  // Extract exports
  analysis.exports = extractExports(content, ext);

  // Extract imports (preliminary — refined in Story 6.2)
  analysis.imports = extractImports(content, ext);

  // Infer tags from path and content
  analysis.tags = inferTags(relPath, content, ext);

  return analysis;
}

/**
 * Infer the purpose of a file from its path and content.
 */
function inferPurpose(relPath, content, ext) {
  const parts = relPath.split(sep);
  const fileName = parts[parts.length - 1];
  const dirName = parts.length > 1 ? parts[parts.length - 2] : '';

  // Check for JSDoc/docstring at top of file
  const topComment = extractTopComment(content, ext);
  if (topComment) return topComment;

  // Infer from path patterns
  const pathLower = relPath.toLowerCase();
  if (pathLower.includes('component')) return `React component in ${dirName}/ directory.`;
  if (pathLower.includes('hook') || fileName.startsWith('use')) return `Custom React hook.`;
  if (pathLower.includes('util') || pathLower.includes('helper')) return `Utility functions for ${dirName}.`;
  if (pathLower.includes('api') || pathLower.includes('route')) return `API route/endpoint handler.`;
  if (pathLower.includes('model') || pathLower.includes('schema')) return `Data model/schema definition.`;
  if (pathLower.includes('test') || pathLower.includes('spec')) return `Test file for ${dirName} module.`;
  if (pathLower.includes('config')) return `Configuration file.`;
  if (pathLower.includes('middleware')) return `Middleware handler.`;
  if (pathLower.includes('context') || pathLower.includes('provider')) return `React context provider.`;
  if (pathLower.includes('service')) return `Service layer for business logic.`;
  if (pathLower.includes('type') || pathLower.includes('interface')) return `TypeScript type definitions.`;
  if (pathLower.includes('style') || ext === '.css' || ext === '.scss') return `Stylesheet for ${dirName}.`;
  if (fileName === 'package.json') return `Package manifest defining project dependencies and scripts.`;
  if (fileName === 'tsconfig.json') return `TypeScript compiler configuration.`;
  if (ext === '.md') return `Documentation file.`;

  return `Source file at ${relPath}.`;
}

/**
 * Extract the top-level comment/docstring from a file.
 */
function extractTopComment(content, ext) {
  if (['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'].includes(ext)) {
    // Match /** ... */ block comments at top
    const match = content.match(/^\s*\/\*\*\s*\n([\s\S]*?)\*\//);
    if (match) {
      return match[1]
        .split('\n')
        .map(l => l.replace(/^\s*\*\s?/, '').trim())
        .filter(l => l && !l.startsWith('@'))
        .join(' ')
        .slice(0, 300);
    }
    // Match // comments at top
    const lineComments = [];
    for (const line of content.split('\n').slice(0, 10)) {
      const m = line.match(/^\s*\/\/\s?(.*)/);
      if (m && m[1].trim()) lineComments.push(m[1].trim());
      else if (line.trim() && !line.match(/^\s*\/\//)) break;
    }
    if (lineComments.length > 0) return lineComments.join(' ').slice(0, 300);
  }

  if (ext === '.py') {
    // Match triple-quoted docstrings
    const match = content.match(/^\s*(?:#.*\n)*\s*(?:"""([\s\S]*?)"""|'''([\s\S]*?)''')/);
    if (match) {
      return (match[1] || match[2]).trim().split('\n').map(l => l.trim()).join(' ').slice(0, 300);
    }
  }

  return null;
}

/**
 * Extract exported symbols from source code.
 */
function extractExports(content, ext) {
  const exports = [];

  if (['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'].includes(ext)) {
    // export default
    const defaultMatch = content.match(/export\s+default\s+(?:function|class|const|let|var)?\s*(\w+)/);
    if (defaultMatch) exports.push({ name: defaultMatch[1], kind: 'default' });

    // export function/const/class
    const namedRegex = /export\s+(?:async\s+)?(?:function|const|let|var|class|interface|type|enum)\s+(\w+)/g;
    let m;
    while ((m = namedRegex.exec(content)) !== null) {
      if (!exports.find(e => e.name === m[1])) {
        exports.push({ name: m[1], kind: 'named' });
      }
    }

    // export { ... }
    const reExportMatch = content.match(/export\s*\{([^}]+)\}/g);
    if (reExportMatch) {
      for (const re of reExportMatch) {
        const inner = re.match(/\{([^}]+)\}/);
        if (inner) {
          for (const sym of inner[1].split(',')) {
            const name = sym.trim().split(/\s+as\s+/)[0].trim();
            if (name && !exports.find(e => e.name === name)) {
              exports.push({ name, kind: 're-export' });
            }
          }
        }
      }
    }
  }

  if (ext === '.py') {
    // def / class at module level
    const defRegex = /^(?:def|class|async\s+def)\s+(\w+)/gm;
    let m;
    while ((m = defRegex.exec(content)) !== null) {
      if (!m[1].startsWith('_')) {
        exports.push({ name: m[1], kind: 'function/class' });
      }
    }
  }

  return exports.slice(0, 20); // Limit to top 20 exports
}

/**
 * Extract import statements (preliminary — refined in Story 6.2).
 */
function extractImports(content, ext) {
  const imports = [];

  if (['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'].includes(ext)) {
    // import ... from '...'
    const importFromRegex = /import\s+(?:[\s\S]*?)\s+from\s+['"]([^'"]+)['"]/g;
    let m;
    while ((m = importFromRegex.exec(content)) !== null) {
      imports.push({ source: m[1], kind: 'import' });
    }

    // require('...')
    const requireRegex = /require\s*\(\s*['"]([^'"]+)['"]\s*\)/g;
    while ((m = requireRegex.exec(content)) !== null) {
      imports.push({ source: m[1], kind: 'require' });
    }

    // import '...' (side-effect imports)
    const sideEffectRegex = /import\s+['"]([^'"]+)['"]/g;
    while ((m = sideEffectRegex.exec(content)) !== null) {
      if (!imports.find(i => i.source === m[1])) {
        imports.push({ source: m[1], kind: 'side-effect' });
      }
    }
  }

  if (ext === '.py') {
    // import X / from X import Y
    const pyImportRegex = /^(?:from\s+([\w.]+)\s+import|import\s+([\w.]+))/gm;
    let m;
    while ((m = pyImportRegex.exec(content)) !== null) {
      imports.push({ source: m[1] || m[2], kind: 'python' });
    }
  }

  if (ext === '.css' || ext === '.scss') {
    // @import '...' / @use '...'
    const cssImportRegex = /@(?:import|use)\s+['"]([^'"]+)['"]/g;
    let m;
    while ((m = cssImportRegex.exec(content)) !== null) {
      imports.push({ source: m[1], kind: 'css' });
    }
  }

  return imports;
}

/**
 * Infer tags from file path and content.
 */
function inferTags(relPath, content, ext) {
  const tags = new Set();
  const pathLower = relPath.toLowerCase();

  // Extension-based tags
  if (['.ts', '.tsx'].includes(ext)) tags.add('typescript');
  if (['.js', '.jsx', '.mjs', '.cjs'].includes(ext)) tags.add('javascript');
  if (ext === '.py') tags.add('python');
  if (ext === '.css' || ext === '.scss') tags.add('styles');
  if (ext === '.md') tags.add('documentation');
  if (ext === '.json') tags.add('config');
  if (ext === '.yaml' || ext === '.yml') tags.add('config');
  if (ext === '.html') tags.add('html');
  if (ext === '.sh') tags.add('shell');

  // Path-based tags
  if (pathLower.includes('component')) tags.add('component');
  if (pathLower.includes('hook') || basename(relPath).startsWith('use')) tags.add('hook');
  if (pathLower.includes('api') || pathLower.includes('route')) tags.add('api');
  if (pathLower.includes('test') || pathLower.includes('spec')) tags.add('test');
  if (pathLower.includes('util') || pathLower.includes('helper')) tags.add('utility');
  if (pathLower.includes('config')) tags.add('config');
  if (pathLower.includes('middleware')) tags.add('middleware');
  if (pathLower.includes('context') || pathLower.includes('provider')) tags.add('context');
  if (pathLower.includes('service')) tags.add('service');
  if (pathLower.includes('model') || pathLower.includes('schema')) tags.add('model');
  if (pathLower.includes('type') || pathLower.includes('interface')) tags.add('types');
  if (pathLower.includes('style')) tags.add('styles');
  if (pathLower.includes('layout')) tags.add('layout');
  if (pathLower.includes('page')) tags.add('page');

  // Content-based tags
  if (content.includes('useState') || content.includes('useEffect')) tags.add('react');
  if (content.includes('express')) tags.add('express');
  if (content.includes('Next') || content.includes('next/')) tags.add('nextjs');
  if (content.includes('prisma')) tags.add('prisma');
  if (content.includes('jwt') || content.includes('JWT')) tags.add('authentication');
  if (content.includes('DynamoDB') || content.includes('dynamodb')) tags.add('dynamodb');
  if (content.includes('S3') || content.includes('s3')) tags.add('s3');
  if (content.includes('Lambda') || content.includes('lambda')) tags.add('lambda');

  return [...tags].slice(0, 10);
}

// ── Article Generation ──

/**
 * Generate preliminary wikilinks from imports.
 * Maps relative imports to wiki article slugs.
 */
function importsToWikilinks(imports, relPath, rootDir, allFilePaths) {
  const links = [];
  const fileDir = dirname(relPath);

  for (const imp of imports) {
    // Only resolve relative/internal imports
    if (!imp.source.startsWith('.') && !imp.source.startsWith('/')) continue;

    // Resolve relative path
    let resolved = join(fileDir, imp.source).replace(/\\/g, '/');
    // Normalize: remove leading ./
    if (resolved.startsWith('./')) resolved = resolved.slice(2);

    // Try to find matching file (with extension resolution)
    const match = resolveImportPath(resolved, allFilePaths);
    if (match) {
      const slug = toSlug(match);
      links.push({ slug, source: imp.source });
    }
  }

  return links;
}

/**
 * Resolve an import path to an actual file path from the known file list.
 */
function resolveImportPath(importPath, allFilePaths) {
  // Direct match
  if (allFilePaths.has(importPath)) return importPath;

  // Try adding extensions
  const extensions = ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'];
  for (const ext of extensions) {
    if (allFilePaths.has(importPath + ext)) return importPath + ext;
  }

  // Try as directory with index file
  for (const ext of extensions) {
    const indexPath = `${importPath}/index${ext}`;
    if (allFilePaths.has(indexPath)) return indexPath;
  }

  return null;
}

/**
 * Generate a wiki article markdown string for a source file.
 */
function generateArticle(analysis, wikilinks, projectId) {
  const dateStr = today();
  const tagsStr = analysis.tags.length > 0 ? `[${analysis.tags.join(', ')}]` : '[]';

  // Build exports section
  let exportsSection = '_No exports detected._';
  if (analysis.exports.length > 0) {
    exportsSection = analysis.exports
      .map(e => `- \`${e.name}\` — ${e.kind} export`)
      .join('\n');
  }

  // Build dependencies section (preliminary wikilinks)
  let depsSection = '_Dependencies will be refined in dependency extraction pass._';
  if (wikilinks.length > 0) {
    depsSection = wikilinks
      .map(l => `- [[${toArticlePath(l.slug)}]] — imported as \`${l.source}\``)
      .join('\n');
  }

  // Build external dependencies
  const externalImports = analysis.imports.filter(i =>
    !i.source.startsWith('.') && !i.source.startsWith('/')
  );
  let externalDepsSection = '';
  if (externalImports.length > 0) {
    externalDepsSection = '\n## External Dependencies\n\n' +
      externalImports.map(i => `- \`${i.source}\``).join('\n') + '\n';
  }

  const article = `---
title: ${analysis.relPath}
type: code
phase: implementation
status: active
maturity: 0.5
created: ${dateStr}
updated: ${dateStr}
createdByEpic: bootstrap
createdByStory: bootstrap-scan
tags: ${tagsStr}
---

## Purpose

${analysis.purpose}

## Key Exports

${exportsSection}

## Dependencies

${depsSection}

## Dependents

_Dependents will be populated in dependency extraction pass._
${externalDepsSection}
## Signals

- File contains ${analysis.lineCount} lines of ${analysis.ext.slice(1)} code
- ${analysis.exports.length} exported symbol(s) detected
- ${analysis.imports.length} import statement(s) detected

## Missing Signals

- Detailed behavioral analysis not yet performed
- Test coverage unknown
- Performance characteristics not assessed
`;

  return article;
}

// ── Pipeline Event Emission (stub — real implementation uses DynamoDB) ──

/**
 * Emit a pipeline progress event.
 * In production, this writes to futurator-agent-events DynamoDB table.
 * For standalone CLI usage, it logs to stdout.
 */
function emitEvent(event) {
  log('info', `Pipeline event: ${event.type}`, event);
}

// ── Main Bootstrap Scan ──

/**
 * Main bootstrap scan function.
 *
 * @param {string} projectId - Project identifier (e.g., "spyhunter")
 * @param {string} workingDir - Absolute path to project root
 * @param {object} opts - Options
 * @param {number} opts.batchSize - Files per batch (default 20)
 * @param {boolean} opts.json - Output JSON results
 * @param {function} opts.onProgress - Progress callback
 * @returns {object} Scan results with manifest
 */
export async function bootstrapScan(projectId, workingDir, opts = {}) {
  const startTime = Date.now();
  const batchSize = opts.batchSize || DEFAULT_BATCH_SIZE;
  const errors = [];

  log('info', `Starting bootstrap scan for project "${projectId}"`, { workingDir, batchSize });

  // Step 1: Initialize wiki structure
  const knowledgeDir = initWikiStructure(workingDir, projectId);

  // Step 2: Discover files
  log('info', 'Discovering source files...');
  const allFiles = discoverFiles(workingDir);
  const sortedFiles = sortByDepth(allFiles, workingDir);
  const relPaths = sortedFiles.map(f => relative(workingDir, f));

  log('info', `Discovered ${sortedFiles.length} source files`);

  emitEvent({
    type: 'progress',
    stage: 'scan',
    message: `Discovered ${sortedFiles.length} files`,
    totalFiles: sortedFiles.length,
  });

  // Build a set of all relative paths for import resolution
  const allRelPathsSet = new Set(relPaths);

  // Step 3: Process files in batches
  const batches = chunk(sortedFiles, batchSize);
  const manifest = {
    projectId,
    workingDir,
    scanDate: new Date().toISOString(),
    batchSize,
    totalBatches: batches.length,
    scannedFiles: [],
    fileCount: sortedFiles.length,
    articleCount: 0,
    errors: [],
  };

  let filesProcessed = 0;

  for (let batchIdx = 0; batchIdx < batches.length; batchIdx++) {
    const batch = batches[batchIdx];
    log('info', `Processing batch ${batchIdx + 1}/${batches.length} (${batch.length} files)`);

    for (const filePath of batch) {
      const relPath = relative(workingDir, filePath);
      const slug = toSlug(relPath);
      const articlePath = join(knowledgeDir, 'code', `${slug}.md`);

      try {
        // Analyze source file
        const analysis = analyzeFile(filePath, workingDir);
        if (!analysis) {
          errors.push({ file: relPath, error: 'Could not read file' });
          manifest.errors.push({ file: relPath, error: 'Could not read file' });
          continue;
        }

        // Generate preliminary wikilinks from imports
        const wikilinks = importsToWikilinks(analysis.imports, relPath, workingDir, allRelPathsSet);

        // Generate article
        const article = generateArticle(analysis, wikilinks, projectId);

        // Write article to knowledge/code/
        writeFileSync(articlePath, article, 'utf-8');

        manifest.scannedFiles.push({
          sourcePath: relPath,
          articlePath: `knowledge/code/${slug}.md`,
          slug: `code/${slug}`,
          lineCount: analysis.lineCount,
          exports: analysis.exports.length,
          imports: analysis.imports.length,
        });
        manifest.articleCount++;

      } catch (err) {
        log('error', `Failed to process file: ${relPath}`, { error: err.message });
        errors.push({ file: relPath, error: err.message });
        manifest.errors.push({ file: relPath, error: err.message });
      }

      filesProcessed++;
    }

    // Emit batch progress
    emitEvent({
      type: 'progress',
      stage: 'scan',
      batch: batchIdx + 1,
      total: batches.length,
      filesProcessed,
      totalFiles: sortedFiles.length,
      percentage: Math.round((filesProcessed / sortedFiles.length) * 100),
    });

    if (opts.onProgress) {
      opts.onProgress({
        batch: batchIdx + 1,
        totalBatches: batches.length,
        filesProcessed,
        totalFiles: sortedFiles.length,
      });
    }
  }

  // Step 4: Generate index.md
  generateIndex(knowledgeDir, manifest, projectId);

  // Step 5: Update log.md
  const durationMs = Date.now() - startTime;
  appendLog(knowledgeDir, {
    operation: 'bootstrap-scan',
    projectId,
    timestamp: new Date().toISOString(),
    fileCount: manifest.fileCount,
    articleCount: manifest.articleCount,
    errorCount: errors.length,
    durationMs,
    batchSize,
    totalBatches: batches.length,
  });

  // Step 6: Write bootstrap manifest
  manifest.durationMs = durationMs;
  const manifestPath = join(workingDir, '.mycelium', 'bootstrap-manifest.json');
  mkdirSync(dirname(manifestPath), { recursive: true });
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8');

  log('info', `Bootstrap scan complete`, {
    articleCount: manifest.articleCount,
    fileCount: manifest.fileCount,
    errors: errors.length,
    durationMs,
  });

  emitEvent({
    type: 'complete',
    stage: 'scan',
    articleCount: manifest.articleCount,
    fileCount: manifest.fileCount,
    durationMs,
    errors: errors.length,
  });

  return manifest;
}

/**
 * Generate the knowledge/index.md catalog of all articles.
 */
function generateIndex(knowledgeDir, manifest, projectId) {
  const dateStr = today();

  const tableRows = manifest.scannedFiles
    .map(f => `| ${f.sourcePath} | code | implementation | active | \`${f.articlePath}\` |`)
    .join('\n');

  const content = `---
title: Knowledge Index — ${projectId}
type: system
phase: system
status: active
created: ${dateStr}
updated: ${dateStr}
---

# Knowledge Index

_Auto-generated by the brownfield bootstrap pipeline._

**Total Articles:** ${manifest.articleCount}
**Scan Date:** ${manifest.scanDate}
**Project:** ${projectId}

## Articles

| Title | Type | Phase | Status | Path |
|-------|------|-------|--------|------|
${tableRows}
`;

  writeFileSync(join(knowledgeDir, 'index.md'), content, 'utf-8');
  log('info', `Generated index.md with ${manifest.articleCount} entries`);
}

/**
 * Append an entry to knowledge/log.md.
 */
function appendLog(knowledgeDir, entry) {
  const logPath = join(knowledgeDir, 'log.md');
  let existing = '';
  if (existsSync(logPath)) {
    existing = readFileSync(logPath, 'utf-8');
  }

  const logEntry = `
### ${entry.operation} — ${entry.timestamp}

- **Project:** ${entry.projectId}
- **Files Scanned:** ${entry.fileCount}
- **Articles Generated:** ${entry.articleCount}
- **Errors:** ${entry.errorCount}
- **Duration:** ${(entry.durationMs / 1000).toFixed(1)}s
- **Batch Size:** ${entry.batchSize}
- **Total Batches:** ${entry.totalBatches}
`;

  writeFileSync(logPath, existing + logEntry, 'utf-8');
}

// ── CLI Entry Point ──

async function main() {
  const args = process.argv.slice(2);

  let projectId = null;
  let workingDir = null;
  let batchSize = DEFAULT_BATCH_SIZE;
  let jsonOutput = false;

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--project':
        projectId = args[++i];
        break;
      case '--dir':
      case '--working-dir':
        workingDir = args[++i];
        break;
      case '--batch-size':
        batchSize = parseInt(args[++i], 10);
        break;
      case '--json':
        jsonOutput = true;
        break;
      case '--help':
        console.log(`
Usage: node bootstrap-scan.mjs --project <id> --dir <path> [options]

Options:
  --project <id>       Project identifier (e.g., "spyhunter")
  --dir <path>         Path to project root directory
  --batch-size <n>     Files per batch (default: ${DEFAULT_BATCH_SIZE})
  --json               Output results as JSON
  --help               Show this help message
`);
        process.exit(0);
    }
  }

  if (!projectId || !workingDir) {
    console.error('Error: --project and --dir are required');
    console.error('Usage: node bootstrap-scan.mjs --project <id> --dir /path/to/project');
    process.exit(1);
  }

  if (!existsSync(workingDir)) {
    console.error(`Error: Directory not found: ${workingDir}`);
    process.exit(1);
  }

  try {
    const result = await bootstrapScan(projectId, workingDir, { batchSize, json: jsonOutput });

    if (jsonOutput) {
      console.log(JSON.stringify(result, null, 2));
    }
  } catch (err) {
    console.error('Bootstrap scan failed:', err.message);
    if (!jsonOutput) console.error(err.stack);
    process.exit(1);
  }
}

// Run if executed directly
const isDirectExecution = process.argv[1] && (
  process.argv[1].endsWith('bootstrap-scan.mjs') ||
  process.argv[1].endsWith('bootstrap-scan')
);

if (isDirectExecution) {
  main();
}
