// Plan Retrospect — criteria metadata (rubric §0.6 "Criteria index" as data)
//
// This is the machine-readable transcription of the rubric §0.6 table — the
// single source of truth for each criterion's stage / tag / engine / axis /
// weight / IE-link / fix-link. `rollup.ts` reads `weight`, `tag`, and `engine`
// from here; the index/UI reads `stage`. Detectors reference these ids.
//
// EVERY row of the §0.6 table is transcribed. Do NOT renumber ids (rubric §10:
// stable ids forever). When the rubric adds a row, append it here.
//
// Source: docs/concepts/pipeline-v2/pipeline-quality-rubric.md §0.6 (and the
// per-stage tables §2–§7 which carry the same engine/axis/W — they agree).

import type { StageId } from './types';

/** AGENT/MECH/OUTPUT tag set (rubric §0.1). A criterion may carry several. */
export type CriterionTag = 'AGENT' | 'MECH' | 'OUTPUT';

/** Engine marker (rubric §0.2): DET = deterministic scorer, LLM = The Assessor. */
export type CriterionEngine = 'DET' | 'LLM';

/** Criterion weight (rubric §0.4): 1 minor, 2 normal, 3 critical. */
export type CriterionWeight = 1 | 2 | 3;

export interface CriterionMeta {
  stage: StageId;
  tag: CriterionTag[];
  engine: CriterionEngine;
  /** Cross-cutting axes D1–D6 (rubric §1). */
  axis: string[];
  weight: CriterionWeight;
  /** §8 IE ids this criterion is linked to ('—' rows → []). */
  ieLink: string[];
  /** Fixes-plan F-ids / story refs ('—'/'done' rows → []). */
  fixLink: string[];
}

/**
 * The §0.6 contract as data. Keyed by criterionId.
 *
 * `fixLink` transcribes the §0.6 `fixLink` column literally (the F-ids named
 * there); the per-finding shipped/open *state* lives in `ie-to-f-map.ts`
 * (the `FixRef` authority), not here.
 */
export const CRITERIA_META: Record<string, CriterionMeta> = {
  // ── CONCEPT ──────────────────────────────────────────────────────────────
  'C-R1': {
    stage: 'concept',
    tag: ['AGENT', 'MECH'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'C-R2': {
    stage: 'concept',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  'C-D1': {
    stage: 'concept',
    tag: ['AGENT'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 3,
    ieLink: [],
    fixLink: [],
  },
  'C-D2': {
    stage: 'concept',
    tag: ['AGENT'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  'C-D3': {
    stage: 'concept',
    tag: ['AGENT'],
    engine: 'LLM',
    axis: ['D6'],
    weight: 3,
    ieLink: [],
    fixLink: [],
  },
  'C-D4': {
    stage: 'concept',
    tag: ['AGENT'],
    engine: 'DET',
    axis: ['D4'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  'C-D5': {
    stage: 'concept',
    tag: ['AGENT'],
    engine: 'DET',
    axis: ['D2'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'C-P1': {
    stage: 'concept',
    tag: ['AGENT', 'MECH'],
    engine: 'LLM',
    axis: ['D3'],
    weight: 3,
    ieLink: [],
    fixLink: [],
  },
  'C-P2': {
    stage: 'concept',
    tag: ['AGENT', 'MECH'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 3,
    ieLink: [],
    fixLink: [],
  },
  'C-P3': {
    stage: 'concept',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D1', 'D2'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'C-P4': {
    stage: 'concept',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  'C-P5': {
    stage: 'concept',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D3'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'C-G1': {
    stage: 'concept',
    tag: ['MECH'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'C-G2': {
    stage: 'concept',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D5'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'C-G3': {
    stage: 'concept',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },

  // ── DEVELOPMENT ──────────────────────────────────────────────────────────
  'D-PW1': {
    stage: 'development',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D2', 'D5'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'D-PW2': {
    stage: 'development',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D6'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  'D-TA1': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'D-TA2': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 3,
    ieLink: ['IE7'],
    fixLink: ['F7'],
  },
  'D-TA3': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D1'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'D-TA4': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D1', 'D6'],
    weight: 3,
    ieLink: ['IE15'],
    fixLink: ['F13'],
  },
  'D-TA5': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D1', 'D2'],
    weight: 1,
    ieLink: [],
    fixLink: ['F13'],
  },
  'D-DV1': {
    stage: 'development',
    tag: ['AGENT'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 3,
    ieLink: [],
    fixLink: [],
  },
  'D-DV2': {
    stage: 'development',
    tag: ['AGENT'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'D-DV3': {
    stage: 'development',
    tag: ['AGENT'],
    engine: 'LLM',
    axis: ['D3'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'D-RV1': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'D-RV2': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D2', 'D5'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'D-RV3': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D5'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'D-CC1': {
    stage: 'development',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 3,
    ieLink: ['IE1'],
    fixLink: ['F1'],
  },
  'D-CC2': {
    stage: 'development',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 3,
    ieLink: ['IE1'],
    fixLink: ['F1'],
  },
  'D-CC3': {
    stage: 'development',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 2,
    ieLink: ['IE1'],
    fixLink: ['F1'],
  },
  'D-MG1': {
    stage: 'development',
    tag: ['MECH', 'OUTPUT'],
    engine: 'DET',
    axis: ['D1'],
    weight: 3,
    ieLink: [],
    fixLink: [],
  },
  'D-MG2': {
    stage: 'development',
    tag: ['MECH', 'OUTPUT'],
    engine: 'DET',
    axis: ['D4'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'D-MG3': {
    stage: 'development',
    tag: ['MECH', 'OUTPUT'],
    engine: 'DET',
    axis: ['D4'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  'D-MG4': {
    stage: 'development',
    tag: ['MECH', 'OUTPUT'],
    engine: 'DET',
    axis: ['D2'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  'D-VQ1': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D1'],
    weight: 3,
    ieLink: ['IE9'],
    fixLink: ['F8'],
  },
  'D-VQ2': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 2,
    ieLink: [],
    fixLink: ['F8'],
  },
  'D-VQ3': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D2', 'D5'],
    weight: 3,
    ieLink: ['IE8'],
    fixLink: ['F8'],
  },
  'D-VQ4': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D4', 'D6'],
    weight: 2,
    ieLink: [],
    fixLink: ['F8'],
  },
  'D-VQ5': {
    stage: 'development',
    tag: ['AGENT', 'MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'D-KC1': {
    stage: 'development',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  'D-KC2': {
    stage: 'development',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 3,
    ieLink: ['IE16'],
    fixLink: ['F14'],
  },
  'D-KC3': {
    stage: 'development',
    tag: ['MECH', 'OUTPUT'],
    engine: 'DET',
    axis: ['D4'],
    weight: 2,
    ieLink: ['IE17', 'IE19'],
    fixLink: ['F14', 'F15', 'F17'],
  },
  'D-KC4': {
    stage: 'development',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D5'],
    weight: 2,
    ieLink: ['IE17'],
    fixLink: ['F16'],
  },
  'D-KC5': {
    stage: 'development',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 2,
    ieLink: ['IE18'],
    fixLink: ['F17'],
  },
  'D-KC6': {
    stage: 'development',
    tag: ['OUTPUT'],
    engine: 'DET',
    axis: ['D6'],
    weight: 1,
    ieLink: [],
    fixLink: ['F18'],
  },
  'D-WS1': {
    stage: 'development',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 2,
    ieLink: ['IE11'],
    fixLink: ['F10'],
  },
  'D-WS2': {
    stage: 'development',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 2,
    ieLink: [],
    fixLink: ['F10'],
  },
  SK1: {
    stage: 'development',
    tag: ['MECH', 'AGENT', 'OUTPUT'],
    engine: 'DET',
    axis: ['D6'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  SK2: {
    stage: 'development',
    tag: ['MECH', 'AGENT', 'OUTPUT'],
    engine: 'DET',
    axis: ['D3'],
    weight: 3,
    ieLink: ['IE25'],
    fixLink: ['F24'],
  },
  SK3: {
    stage: 'development',
    tag: ['MECH', 'AGENT', 'OUTPUT'],
    engine: 'DET',
    axis: ['D3'],
    weight: 2,
    ieLink: ['IE27'],
    fixLink: ['F27'],
  },
  SK4: {
    stage: 'development',
    tag: ['MECH', 'AGENT', 'OUTPUT'],
    engine: 'DET',
    axis: ['D1', 'D6'],
    weight: 2,
    ieLink: ['IE26'],
    fixLink: ['F25'],
  },
  SK5: {
    stage: 'development',
    tag: ['MECH', 'AGENT', 'OUTPUT'],
    engine: 'DET',
    axis: ['D4'],
    weight: 3,
    ieLink: ['IE28'],
    fixLink: ['4.2', 'F26'],
  },
  SK6: {
    stage: 'development',
    tag: ['MECH', 'AGENT', 'OUTPUT'],
    engine: 'DET',
    axis: ['D5', 'D4'],
    weight: 2,
    ieLink: ['IE29'],
    fixLink: ['F5', 'F28'],
  },

  // ── QA ───────────────────────────────────────────────────────────────────
  'Q-C1': {
    stage: 'qa',
    tag: ['AGENT'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'Q-C2': {
    stage: 'qa',
    tag: ['MECH'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 3,
    ieLink: [],
    fixLink: [],
  },
  'Q-C3': {
    stage: 'qa',
    tag: ['AGENT'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'Q-C4': {
    stage: 'qa',
    tag: ['MECH'],
    engine: 'LLM',
    axis: ['D1', 'D5'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'Q-C5': {
    stage: 'qa',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  'Q-C6': {
    stage: 'qa',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 3,
    ieLink: ['IE14'],
    fixLink: ['F12'],
  },
  'Q-C7': {
    stage: 'qa',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D1', 'D5'],
    weight: 3,
    ieLink: ['IE15'],
    fixLink: ['F12'],
  },
  'Q-C8': {
    stage: 'qa',
    tag: ['AGENT'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 2,
    ieLink: [],
    fixLink: ['F12'],
  },
  'Q-C9': {
    stage: 'qa',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4', 'D5'],
    weight: 3,
    ieLink: ['IE13'],
    fixLink: ['F11'],
  },

  // ── DEPLOYMENT ─────────────────────────────────────────────────────────────
  'DP-B1': {
    stage: 'deployment',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D1'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'DP-B2': {
    stage: 'deployment',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D1'],
    weight: 2,
    ieLink: ['IE21'],
    fixLink: ['F20'],
  },
  'DP-L1': {
    stage: 'deployment',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D5'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'DP-L2': {
    stage: 'deployment',
    tag: ['MECH', 'OUTPUT'],
    engine: 'DET',
    axis: ['D1', 'D2'],
    weight: 2,
    ieLink: ['IE22'],
    fixLink: ['F22'],
  },
  'DP-R1': {
    stage: 'deployment',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4', 'D5'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'DP-S1': {
    stage: 'deployment',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 3,
    ieLink: [],
    fixLink: [],
  },
  'DP-S2': {
    stage: 'deployment',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D1', 'D4'],
    weight: 2,
    ieLink: [],
    fixLink: ['F21'],
  },
  'DP-D1': {
    stage: 'deployment',
    tag: ['OUTPUT'],
    engine: 'DET',
    axis: ['D4'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  'DP-T1': {
    stage: 'deployment',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  'DP-U1': {
    stage: 'deployment',
    tag: ['MECH', 'OUTPUT'],
    engine: 'DET',
    axis: ['D1', 'D4'],
    weight: 3,
    ieLink: ['IE20'],
    fixLink: ['F19'],
  },
  'DP-I1': {
    stage: 'deployment',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4', 'D5'],
    weight: 3,
    ieLink: ['IE13'],
    fixLink: ['F11'],
  },
  'DP-E1': {
    stage: 'deployment',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 2,
    ieLink: [],
    fixLink: ['F22'],
  },
  'DP-O1': {
    stage: 'deployment',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 2,
    ieLink: ['IE24'],
    fixLink: ['F21'],
  },

  // ── PUBLISH ─────────────────────────────────────────────────────────────────
  'P-A1': {
    stage: 'publish',
    tag: ['OUTPUT'],
    engine: 'DET',
    axis: ['D1'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'P-X1': {
    stage: 'publish',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  'P-S1': {
    stage: 'publish',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 3,
    ieLink: [],
    fixLink: [],
  },
  'P-M1': {
    stage: 'publish',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  'P-I1': {
    stage: 'publish',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D5'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },

  // ── OVERVIEW ────────────────────────────────────────────────────────────────
  OV1: {
    stage: 'overview',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  OV2: {
    stage: 'overview',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 3,
    ieLink: ['IE6'],
    fixLink: ['F6'],
  },
  OV3: {
    stage: 'overview',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 2,
    ieLink: [],
    fixLink: [],
  },
  OV4: {
    stage: 'overview',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 3,
    ieLink: ['IE3'],
    fixLink: ['F3'],
  },
  OV5: {
    stage: 'overview',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 2,
    ieLink: ['IE4'],
    fixLink: ['F4'],
  },
  OV6: {
    stage: 'overview',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 2,
    ieLink: ['IE2'],
    fixLink: ['F2'],
  },
  OV7: {
    stage: 'overview',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D2'],
    weight: 1,
    ieLink: ['IE10'],
    fixLink: ['F9'],
  },
  OV8: {
    stage: 'overview',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4', 'D5'],
    weight: 3,
    ieLink: ['IE5'],
    fixLink: ['F5'],
  },
  OV9: {
    stage: 'overview',
    tag: ['AGENT'],
    engine: 'LLM',
    axis: ['D1'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  OV10: {
    stage: 'overview',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D4'],
    weight: 1,
    ieLink: [],
    fixLink: [],
  },
  OV11: {
    stage: 'overview',
    tag: ['MECH'],
    engine: 'DET',
    axis: ['D5', 'D4'],
    weight: 3,
    ieLink: ['IE23'],
    fixLink: ['F23'],
  },
};

/** All criterion ids (stable order = insertion order above). */
export const ALL_CRITERION_IDS = Object.keys(CRITERIA_META);

/** Criterion ids for one stage. */
export function criteriaForStage(stage: StageId): string[] {
  return ALL_CRITERION_IDS.filter((id) => CRITERIA_META[id].stage === stage);
}
