#!/usr/bin/env node
// recon.mjs — Epic A1: one-command deterministic recon for a (migrated) codebase.
//
// Chains the validated pipeline: graphify build (AST, directed, 0 LLM) -> knip (dead-code) ->
// alias-resolve (tsconfig-paths fan-in) -> hotspot-detect (ranked hotspots). Writes everything
// to <repo>/graphify-out/ and a human REPORT.md. Pure-deterministic; ~0 LLM tokens.
//
// USAGE: node recon.mjs <repo> [--src src] [--skip-graphify]
//
// The daemon runs this headless on the EC2 clone for a `refactor-audit` job (Epic B).

import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const args = process.argv.slice(2)
const repo = path.resolve(args[0] || '.')
const flag = (n, d = null) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : d }
const src = flag('--src', 'src')
const skipGraphify = args.includes('--skip-graphify')
const outDir = path.join(repo, 'graphify-out')
fs.mkdirSync(outDir, { recursive: true })

const run = (cmd, cmdArgs, opts = {}) => {
  process.stdout.write(`\n▶ ${cmd} ${cmdArgs.join(' ')}\n`)
  try { return execFileSync(cmd, cmdArgs, { stdio: 'inherit', cwd: repo, ...opts }) }
  catch (e) { if (opts.allowFail) { console.error(`  (non-fatal: exit ${e.status})`); return null } throw e }
}

// resolve a python that can `import graphify`.
// Order: explicit GRAPHIFY_PYTHON env → per-repo saved hint → the conventional
// EC2 daemon venv (kept isolated from system python) → bare python3.
function graphifyPython() {
  const saved = path.join(outDir, '.graphify_python')
  const cands = []
  if (process.env.GRAPHIFY_PYTHON) cands.push(process.env.GRAPHIFY_PYTHON)
  if (fs.existsSync(saved)) cands.push(fs.readFileSync(saved, 'utf8').trim())
  cands.push('/opt/graphify-venv/bin/python')
  cands.push('python3')
  for (const py of cands) {
    try { execFileSync(py, ['-c', 'import graphify'], { stdio: 'ignore' }); return py } catch {}
  }
  return null
}

// 1) graphify build (AST, directed)
if (!skipGraphify) {
  const py = graphifyPython()
  if (!py) { console.error('! graphify not importable. Install: uv tool install graphifyy  (or pip install graphifyy)'); process.exit(2) }
  // fresh audit: remove a stale graph so graphify's overwrite-guard can't pin an old build
  try { fs.rmSync(path.join(outDir, 'graph.json')) } catch {}
  // graphify-build.py exits 3 on a degenerate build — re-raise that as recon's
  // own exit 3 so the daemon can classify it as `degenerate-build` (FR22),
  // distinct from exit 2 (graphify-missing) and exit 1 (other recon error).
  try {
    run(py, [path.join(HERE, 'graphify-build.py'), repo, src, outDir])
  } catch (e) {
    if (e.status === 3) { console.error('! graphify produced a degenerate build (too few nodes/edges)'); process.exit(3) }
    throw e
  }
} else if (!fs.existsSync(path.join(outDir, 'graph.json'))) {
  console.error('! --skip-graphify but no graph.json present'); process.exit(2)
}

// 2) knip dead-code feed (best-effort: knip exits 1 when it finds issues)
try {
  const knipOut = execFileSync('npx', ['--no-install', 'knip', '--reporter', 'json'], { cwd: repo, maxBuffer: 64 * 1024 * 1024 })
  fs.writeFileSync(path.join(outDir, 'knip.json'), knipOut)
  console.log('\n▶ knip → graphify-out/knip.json')
} catch (e) {
  if (e.stdout) { fs.writeFileSync(path.join(outDir, 'knip.json'), e.stdout); console.log('\n▶ knip → graphify-out/knip.json (with issues)') }
  else console.error('\n  (knip unavailable — dead-code feed skipped)')
}

// 3) alias-resolve (correct fan-in)
run('node', [path.join(HERE, 'alias-resolve.mjs'), repo, '--graph', path.join(outDir, 'graph.json'), '--src', src])

// 4) hotspot-detect (ranked hotspots)
run('node', [path.join(HERE, 'hotspot-detect.mjs'), outDir, '--repo', repo])

// 5) REPORT.md
const hs = JSON.parse(fs.readFileSync(path.join(outDir, 'hotspots.json'), 'utf8'))
const ri = (() => { try { return JSON.parse(fs.readFileSync(path.join(outDir, 'resolved-imports.json'), 'utf8')) } catch { return null } })()
const lines = []
lines.push(`# Recon Report — ${path.basename(repo)}`, '')
lines.push(`Generated by recon.mjs (deterministic, ~0 LLM). Counts: ${Object.entries(hs.counts).map(([k, v]) => `${k}=${v}`).join(' · ')}`, '')
if (ri) lines.push(`Files scanned: ${ri.filesScanned} · alias imports resolved: ${ri.aliasResolved} (unresolved: ${ri.aliasUnresolved})`, '')
lines.push('## Hotspots (severity-ranked)', '')
for (const h of hs.hotspots) lines.push(`- **[${h.severity.toUpperCase()} ${Math.round(h.score)}]** ${h.title}`)
lines.push('', '## Top hubs (alias-resolved fan-in)', '')
for (const h of (ri?.hubs || []).slice(0, 15)) lines.push(`- in=${h.inDegree} — ${h.file}`)
lines.push('', '_Next: feed `hotspots.json` to the `/assess-codebase` L3 workflow for an adjudicated plan._')
fs.writeFileSync(path.join(outDir, 'REPORT.md'), lines.join('\n'))

console.log(`\n✅ recon complete → ${path.relative(process.cwd(), outDir)}/`)
console.log(`   graph.json · graph.resolved.json · resolved-imports.json · hotspots.json · knip.json · REPORT.md`)
