/**
 * feature-wiring.ts — Story D (agentic-integration, 2026-05-29).
 *
 * The "registry / generated wiring" conflict-elimination primitive.
 *
 * THE PROBLEM (pacman-2): every render story hand-edits the single hot
 * wiring file (`src/app/page.tsx`) to mount its component, so two parallel
 * stories inevitably collide there. `touchPoints` wave-spreading reduces but
 * cannot eliminate this — it is a pre-hoc LLM guess.
 *
 * THE FIX: features REGISTER THEMSELVES. Each feature is its own file under
 * `src/features/<name>.feature.tsx` exporting a `feature` descriptor + a
 * default component. Adding a feature is an ADDITIVE file create on a
 * disjoint path — never an edit to a shared file. `src/app/page.tsx` is then
 * GENERATED from the union of those files (deterministically, sorted), so no
 * story ever hand-edits it and the single biggest conflict source vanishes.
 *
 * This module is the engine: a pure `generatePageSource()` (unit-tested) and
 * the self-contained generator script + scaffold files shipped into every
 * nextjs-* app via the boilerplate registry's `augmentFiles`. The daemon's
 * post-merge gate runs the generator before `next build`, so the candidate
 * always builds the correctly-integrated page from ALL merged features.
 *
 * See docs/concepts/pipeline-v2/integration-followups-bcd.md (Story D).
 */

export interface FeatureDescriptor {
  /** Stable identifier, also the import alias root. From the file's `slug`. */
  slug: string;
  /** Render order; lower first. Ties broken by slug for determinism. */
  order: number;
  /** Import path relative to `src/app/`, e.g. `../features/pacman.feature`. */
  importPath: string;
  /** PascalCase component identifier used in the generated import. */
  componentName: string;
}

const GENERATED_HEADER = `// @generated by scripts/generate-wiring.mjs — DO NOT EDIT.
// Add a feature by creating src/features/<name>.feature.tsx (see
// src/features/README.md). This file is regenerated from that directory.`;

/** Deterministic order: by \`order\` ascending, then \`slug\` ascending. */
export function sortFeatures(features: FeatureDescriptor[]): FeatureDescriptor[] {
  return [...features].sort((a, b) => a.order - b.order || a.slug.localeCompare(b.slug));
}

/**
 * Generate the full source of `src/app/page.tsx` from a set of feature
 * descriptors. Pure + deterministic — the same feature set always produces
 * byte-identical output, which is what makes the generated file safe to
 * regenerate in any worktree without divergence.
 */
export function generatePageSource(features: FeatureDescriptor[]): string {
  const sorted = sortFeatures(features);

  if (sorted.length === 0) {
    return `${GENERATED_HEADER}

export default function Page() {
  return (
    <main>
      {/* No features registered yet. Add src/features/<name>.feature.tsx. */}
    </main>
  );
}
`;
  }

  const imports = sorted.map((f) => `import ${f.componentName} from '${f.importPath}';`).join('\n');
  const mounts = sorted.map((f) => `      <${f.componentName} key="${f.slug}" />`).join('\n');

  return `${GENERATED_HEADER}

${imports}

export default function Page() {
  return (
    <main>
${mounts}
    </main>
  );
}
`;
}

/**
 * The self-contained generator script shipped into every nextjs-* app as
 * `scripts/generate-wiring.mjs`. It scans `src/features/*.feature.tsx`,
 * extracts each file's `slug`/`order` from its exported `feature` descriptor
 * (static regex parse — never executes app code), and writes
 * `src/app/page.tsx`. Kept dependency-free (node built-ins only) so it runs
 * in a bare app checkout.
 *
 * NOTE: the generation algorithm is intentionally mirrored from
 * `generatePageSource` above; the end-to-end test (feature-wiring.test.ts)
 * runs THIS shipped script against a temp dir and asserts its output matches
 * `generatePageSource`, so the two cannot silently drift.
 */
export const FEATURE_WIRING_GENERATOR_MJS = `#!/usr/bin/env node
/**
 * @generated scaffold — generate-wiring.mjs (Story D, agentic-integration).
 *
 * Regenerates src/app/page.tsx from src/features/*.feature.tsx so no story
 * ever hand-edits the hot wiring file. Each feature file must export:
 *   export const feature = { slug: 'kebab-id', order: 10 };
 *   export default function Foo() { ... }
 * Run automatically by the wave-merge build gate (and wire as a package.json
 * \`prebuild\` script to regenerate on every local build).
 */
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const ROOT = process.cwd();
const FEATURES_DIR = join(ROOT, 'src', 'features');
const OUT = join(ROOT, 'src', 'app', 'page.tsx');

function pascal(slug) {
  return slug
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join('');
}

function parseFeature(file, src) {
  // Static parse — never execute app code. slug is required; order defaults 100.
  const slugM = src.match(/slug\\s*:\\s*['"\\\`]([^'"\\\`]+)['"\\\`]/);
  if (!slugM) return null;
  const orderM = src.match(/order\\s*:\\s*(-?\\d+)/);
  const slug = slugM[1];
  return {
    slug,
    order: orderM ? parseInt(orderM[1], 10) : 100,
    importPath: '../features/' + file.replace(/\\.tsx$/, ''),
    componentName: pascal(slug) + 'Feature',
  };
}

function collect() {
  if (!existsSync(FEATURES_DIR)) return [];
  return readdirSync(FEATURES_DIR)
    .filter((f) => f.endsWith('.feature.tsx'))
    .map((f) => parseFeature(f, readFileSync(join(FEATURES_DIR, f), 'utf8')))
    .filter(Boolean);
}

function render(features) {
  const header =
    '// @generated by scripts/generate-wiring.mjs — DO NOT EDIT.\\n' +
    '// Add a feature by creating src/features/<name>.feature.tsx (see\\n' +
    '// src/features/README.md). This file is regenerated from that directory.';
  const sorted = [...features].sort((a, b) => a.order - b.order || a.slug.localeCompare(b.slug));
  if (sorted.length === 0) {
    return (
      header +
      '\\n\\nexport default function Page() {\\n  return (\\n    <main>\\n' +
      '      {/* No features registered yet. Add src/features/<name>.feature.tsx. */}\\n' +
      '    </main>\\n  );\\n}\\n'
    );
  }
  const imports = sorted.map((f) => 'import ' + f.componentName + " from '" + f.importPath + "';").join('\\n');
  const mounts = sorted.map((f) => '      <' + f.componentName + ' key="' + f.slug + '" />').join('\\n');
  return (
    header +
    '\\n\\n' +
    imports +
    '\\n\\nexport default function Page() {\\n  return (\\n    <main>\\n' +
    mounts +
    '\\n    </main>\\n  );\\n}\\n'
  );
}

const features = collect();
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, render(features), 'utf8');
console.log('[generate-wiring] wrote ' + OUT + ' from ' + features.length + ' feature(s)');
`;

/** Shipped to `src/features/README.md` — the convention for agents + humans. */
export const FEATURE_REGISTRY_README = `# Feature registry — additive wiring (no hot-file conflicts)

\`src/app/page.tsx\` is **generated** by \`scripts/generate-wiring.mjs\` from the
\`*.feature.tsx\` files in this directory. **Never hand-edit \`page.tsx\`** — your
change will be overwritten on the next build.

## Add a feature

Create \`src/features/<name>.feature.tsx\`:

\`\`\`tsx
export const feature = { slug: 'pacman', order: 10 };

export default function PacmanFeature() {
  return <PacmanCanvas />;
}
\`\`\`

- \`slug\` — stable kebab-case id (required).
- \`order\` — render order, lower first (optional, defaults to 100).
- default export — the component mounted on the home page.

Because each feature is its own file on a disjoint path, two stories adding
two features never conflict — the single biggest merge-conflict source
(every story editing \`page.tsx\`) is eliminated by construction.
`;

/**
 * Shipped to `.gitattributes` (appended). Marks the generated wiring file so
 * GitHub collapses its diffs and tooling treats it as generated. (Full
 * conflict elimination — git-ignoring page.tsx so stories never commit it —
 * is the external base-scaffold follow-up; see integration-followups-bcd.md.)
 */
export const GITATTRIBUTES_GENERATED = `# Story D (agentic-integration) — generated wiring file.
src/app/page.tsx linguist-generated=true
`;
